version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
      kubectl: 1.18
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli
      - echo "Dependencies installed."
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "Pulling base image..."
  build:
    commands:
      - echo "Updating EKS cluster..."
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_DEFAULT_REGION
      - find . -name "*.yaml" -exec kubectl apply -f {} \;
      - echo "EKS cluster updated."
  post_build:
    commands:
      - exho "DONE"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
