version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - echo Setting up kubeconfig...
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_DEFAULT_REGION

  pre_build:
    commands:
      - echo Pre-build phase...
      - kubectl get nodes

  build:
    commands:
      - echo Build started on `date`
      - echo Applying Kubernetes manifests...
      - find ./ -name '*.yaml' ! -name 'namespace.yaml' -exec kubectl apply -f {} \;

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  discard-paths: yes
