version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo Installing kubectl...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - echo "AWS Identity:"
      - aws sts get-caller-identity
      - echo "Available EKS clusters:"
      - aws eks list-clusters
      - echo "Cluster name: $CLUSTER_NAME"
      - echo "Updating kubeconfig..."
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_DEFAULT_REGION
      - echo "Retrieving EKS token..."
      - TOKEN=$(aws eks get-token --cluster-name $CLUSTER_NAME)
      - echo "Applying token to kubectl..."
      - echo $TOKEN | kubectl apply -f -
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Deploying to EKS...
      - find . -name "*.yaml" -exec kubectl apply -f {} --validate=false \;
      - echo Deployment completed on `date`

artifacts:
  files: '**/*'
