version: 0.2

phases:
  install:
    runtime-versions:
      kubectl: 1.18
    commands:
      - echo Installing kubectl
      - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
  pre_build:
    commands:
      - echo Logging in to Amazon EKS
      - aws eks update-kubeconfig --name $CLUSTER_NAME
  build:
    commands:
      - echo Applying Kubernetes manifests
      - find . -name "*.yaml" -exec kubectl apply -f {} \;
