version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install --upgrade awscli
      - curl -LO "https://dl.k8s.io/release/v1.30.2/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
      - kubectl version --short --client
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION
      - echo Authenticating with the EKS cluster...
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_DEFAULT_REGION  --profile anotheracc
      - kubectl get nodes # Verify authentication

  build:
    commands:
      - echo Applying Kubernetes manifests...
      - find . -name "*.yaml" -exec kubectl apply -f {} --validate=false \;
  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
  discard-paths: yes
