apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-nginx
  namespace: medium
  labels:
    app: custom-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: custom-nginx
  template:
    metadata:
      labels:
        app: custom-nginx
    spec:
      containers:
      - name: custom-nginx
        image: <Your-Cluster-ID>.dkr.ecr.<AWS-ZONE>.amazonaws.com/<IMAGE-NAME>:<IMAGE-TAG>
        ports:
        - containerPort: 80
