apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-nginx
  namespace: medium
  labels:
    app: custom-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: custom-nginx
  template:
    metadata:
      labels:
        app: custom-nginx
    spec:
      containers:
      - name: custom-nginx
        image: 192.168.1.103:8082/custom-nginx:1.3
        ports:
        - containerPort: 80
